FORMAT: 1A
# Rails API Template

# Group Passwords

## Create Password [api/v1/users/password]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: kendrick@hayes.name

    + Body

            {"email":"notvalid@example.com"}

+ Response 404 ()

    + Body

            {
              "error": "Unable to find user with email 'notvalid@example.com'."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: allen@keebler.net

    + Body

            {"email":"allen@keebler.net"}

+ Response 200 ()

    + Body

            {
              "success": true,
              "message": "An email has been sent to 'allen@keebler.net' containing instructions for resetting your password."
            }

## Update Password [api/v1/users/password]

### Update [PUT]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: simone@kiehn.net

    + Body

            {"password":"123456789","password_confirmation":""}

+ Response 422 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1664993493
            uid: simone@kiehn.net

    + Body

            {
              "success": false,
              "errors": {
                "password_confirmation": [
                  "doesn't match Password"
                ],
                "full_messages": [
                  "Password confirmation doesn't match Password"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: debroah.heidenreich@wilkinson-rutherford.net

    + Body

            {"password":"123456789","password_confirmation":"123456789"}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1664993493
            uid: debroah.heidenreich@wilkinson-rutherford.net

    + Body

            {
              "success": true,
              "data": {
                "id": 14,
                "provider": "email",
                "allow_password_change": false,
                "email": "debroah.heidenreich@wilkinson-rutherford.net",
                "uid": "debroah.heidenreich@wilkinson-rutherford.net",
                "first_name": "Anitra Wunsch",
                "last_name": "Treutel",
                "username": "jeanne_koepp",
                "created_at": "2020-10-05T18:11:32.928Z",
                "updated_at": "2020-10-05T18:11:33.179Z"
              },
              "message": "Your password has been successfully updated."
            }

## Edit Password [api/v1/users/password/edit]

### Edit [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: rayford.tillman@medhurst-kris.biz

+ Response 302 ()

    + Body

            <html><body>You are being <a href="http://127.0.0.1:3000?access-token=1234567890123456789012&amp;client=abcdefghijklmnopqrstuv&amp;client_id=abcdefghijklmnopqrstuv&amp;config=&amp;expiry=1664993493&amp;reset_password=true&amp;token=1234567890123456789012&amp;uid=rayford.tillman%40medhurst-kris.biz">redirected</a>.</body></html>

# Group Sessions

## Session [api/v1/users/sign_in]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: whitney_schultz@mraz-jakubowski.com

    + Body

            {"user":{"email":"whitney_schultz@mraz-jakubowski.com","password":"wrong-password"}}

+ Response 401 ()

    + Body

            {
              "error": "Invalid login credentials. Please try again."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: saul.wolff@simonis.org

    + Body

            {"user":{"email":"saul.wolff@simonis.org","password":"0DgM3wJv"}}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1664993490
            uid: saul.wolff@simonis.org

    + Body

            {
              "user": {
                "id": 1,
                "email": "saul.wolff@simonis.org",
                "uid": "saul.wolff@simonis.org",
                "provider": "email",
                "allow_password_change": false,
                "first_name": "Rep. Vito Blick",
                "last_name": "Blick",
                "username": "alda.quigley",
                "created_at": "2020-10-05T18:11:29.974Z",
                "updated_at": "2020-10-05T18:11:30.288Z"
              }
            }

## Session [api/v1/users/sign_out]

### Delete [DELETE]

+ Request Bad

    + Headers

            Access-Token: notvalidtoken
            Client: abcdefghijklmnopqrstuv
            Uid: rob_schaden@bartell.name

+ Response 404 ()

    + Body

            {
              "error": "User was not found or was not logged in."
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: joaquin.pagac@weissnat-botsford.info

+ Response 200 ()

    + Body

            {
              "success": true
            }

# Group Settings

## Must Update [api/v1/settings/must_update]

### Get [GET]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: leigh@schamberger.net

+ Response 200 ()

    + Body

            {
              "must_update": true
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: stephen.prosacco@glover.info

+ Response 200 ()

    + Body

            {
              "must_update": false
            }

# Group Status

## Status [api/v1/status]

### Get [GET]

+ Request Ok

+ Response 200 ()

    + Body

            {
              "online": true
            }

# Group Users

## Create User [api/v1/users]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: chassidy_roob@willms.com

    + Body

            {"user":{"email":"not-valid","password":"HtOnJ6cH1dHo","username":"rosaria.anderson","first_name":"Milly Lang","last_name":"Rohan","uid":"9f4a3eea-9f7f-42fd-8dc1-5eca51131f1d"}}

+ Response 422 ()

    + Body

            {
              "status": "error",
              "data": {
                "id": null,
                "email": "not-valid",
                "allow_password_change": false,
                "first_name": "Milly Lang",
                "last_name": "Rohan",
                "username": "rosaria.anderson",
                "created_at": null,
                "updated_at": null,
                "provider": "email",
                "uid": "not-valid"
              },
              "errors": {
                "email": [
                  "is not an email"
                ],
                "full_messages": [
                  "Email is not an email"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: dallas@anderson.io

    + Body

            {"user":{"email":"ladonna@beier-kuvalis.co","password":"HjVvQzAh","username":"audrea","first_name":"Everett Brown","last_name":"Kirlin","uid":"cd14597d-91d4-4ae5-93b2-d8c6b4b12fd1"}}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1664993492
            uid: ladonna@beier-kuvalis.co

    + Body

            {
              "user": {
                "id": 11,
                "email": "ladonna@beier-kuvalis.co",
                "allow_password_change": false,
                "first_name": "Everett Brown",
                "last_name": "Kirlin",
                "username": "audrea",
                "created_at": "2020-10-05T18:11:32.258Z",
                "updated_at": "2020-10-05T18:11:32.363Z",
                "provider": "email",
                "uid": "ladonna@beier-kuvalis.co"
              }
            }

## Update User [api/v1/user]

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: pasty@bosco.co

    + Body

            {"user":{"username":"new username"}}

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1664993491
            uid: pasty@bosco.co

    + Body

            {
              "user": {
                "id": 7,
                "email": "pasty@bosco.co",
                "name": "Olin Senger Reilly",
                "username": "new username"
              }
            }

## Show User [api/v1/user]

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 1234567890123456789012
            Client: abcdefghijklmnopqrstuv
            Uid: armando@purdy.co

+ Response 200 ()

    + Headers

            access-token: 1234567890123456789012
            token-type: Bearer
            client: abcdefghijklmnopqrstuv
            expiry: 1664993491
            uid: armando@purdy.co

    + Body

            {
              "user": {
                "id": 8,
                "email": "armando@purdy.co",
                "name": "Sherie Cartwright CPA Schoen",
                "username": "tai_kuvalis"
              }
            }
