FORMAT: 1A
# Rails API Template

# Group Passwords

## Create Password [api/v1/users/password]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: UKbQD61T64pYPg98xUsOng
            Client: 0zt8TiSYKKwhCplSsLIj0g
            Uid: cory@schumm.org

    + Body

            {"email":"notvalid@example.com"}

+ Response 404 ()

    + Body

            {
              "error": "Unable to find user with email 'notvalid@example.com'."
            }

+ Request Ok

    + Headers

            Access-Token: vYsxWf4qWfEMBhq865tQ9Q
            Client: OyXpxSQYZAItx4Ds6n8_qw
            Uid: katelyn.lockman@weber-weissnat.io

    + Body

            {"email":"katelyn.lockman@weber-weissnat.io"}

+ Response 200 ()

    + Body

            {
              "success": true,
              "message": "An email has been sent to 'katelyn.lockman@weber-weissnat.io' containing instructions for resetting your password."
            }

## Update Password [api/v1/users/password]

### Update [PUT]

+ Request Bad

    + Headers

            Access-Token: p4MOyBb6k8KXIzsu5N4tSg
            Client: i16yvrJFxnY-giI-JuIl8w
            Uid: clayton_terry@auer.org

    + Body

            {"password":"123456789","password_confirmation":""}

+ Response 422 ()

    + Headers

            access-token: p4MOyBb6k8KXIzsu5N4tSg
            token-type: Bearer
            client: i16yvrJFxnY-giI-JuIl8w
            expiry: 1664985544
            uid: clayton_terry@auer.org

    + Body

            {
              "success": false,
              "errors": {
                "password_confirmation": [
                  "doesn't match Password"
                ],
                "full_messages": [
                  "Password confirmation doesn't match Password"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: ILBM0ACf-LE1oxBn4-R68Q
            Client: ivf4SFXWQJoyHXTdXx3CYQ
            Uid: marshall.buckridge@watsica.org

    + Body

            {"password":"123456789","password_confirmation":"123456789"}

+ Response 200 ()

    + Headers

            access-token: ILBM0ACf-LE1oxBn4-R68Q
            token-type: Bearer
            client: ivf4SFXWQJoyHXTdXx3CYQ
            expiry: 1664985544
            uid: marshall.buckridge@watsica.org

    + Body

            {
              "success": true,
              "data": {
                "id": 9,
                "provider": "email",
                "allow_password_change": false,
                "email": "marshall.buckridge@watsica.org",
                "uid": "marshall.buckridge@watsica.org",
                "first_name": "Wai Hahn",
                "last_name": "Funk",
                "username": "delpha",
                "created_at": "2020-10-05T15:59:04.280Z",
                "updated_at": "2020-10-05T15:59:04.408Z"
              },
              "message": "Your password has been successfully updated."
            }

## Edit Password [api/v1/users/password/edit]

### Edit [GET]

+ Request Ok

    + Headers

            Access-Token: viHNOystDLtVhdJtRxhbqg
            Client: uLQAzASlWUU2CgTegZFvMw
            Uid: vicente@hartmann-emmerich.name

+ Response 302 ()

    + Body

            <html><body>You are being <a href="http://127.0.0.1:3000?access-token=Ka9TXMNgDs7-KZtA4Y-_jQ&amp;client=DR-KBtlZgNjxZtyBkSn9Nw&amp;client_id=DR-KBtlZgNjxZtyBkSn9Nw&amp;config=&amp;expiry=1664985544&amp;reset_password=true&amp;token=Ka9TXMNgDs7-KZtA4Y-_jQ&amp;uid=vicente%40hartmann-emmerich.name">redirected</a>.</body></html>

# Group Sessions

## Session [api/v1/users/sign_out]

### Delete [DELETE]

+ Request Bad

    + Headers

            Access-Token: notvalidtoken
            Client: 3HfQ0pkhPBDG0IBC9WiwNA
            Uid: birdie.rau@tillman.net

+ Response 404 ()

    + Body

            {
              "error": "User was not found or was not logged in."
            }

+ Request Ok

    + Headers

            Access-Token: Iis9s-QPmwKWvOS4ZG_hpQ
            Client: -Ro0Q6h-Ck2l1uqYbQQYNg
            Uid: genny.leffler@hamill.info

+ Response 200 ()

    + Body

            {
              "success": true
            }

## Session [api/v1/users/sign_in]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: Z1adE_uXn4NB5Z1Jg3PGGg
            Client: CcZrnZGYIHxeNC3Z6184Pw
            Uid: nicholas_mueller@lueilwitz-russel.org

    + Body

            {"user":{"email":"nicholas_mueller@lueilwitz-russel.org","password":"wrong-password"}}

+ Response 401 ()

    + Body

            {
              "error": "Invalid login credentials. Please try again."
            }

+ Request Ok

    + Headers

            Access-Token: VrcLJDXlJ4BK2tleKxU9zQ
            Client: KZJBhs6fxHsnRNLkHTOyBw
            Uid: valerie.klein@kunze.io

    + Body

            {"user":{"email":"valerie.klein@kunze.io","password":"4Fc9WaIkB38qQqGz"}}

+ Response 200 ()

    + Headers

            access-token: KOAiRm8plzHJSLk-KBKwyA
            token-type: Bearer
            client: pYV0nbH9RR_8sI3TYAIWBQ
            expiry: 1664985543
            uid: valerie.klein@kunze.io

    + Body

            {
              "user": {
                "id": 3,
                "email": "valerie.klein@kunze.io",
                "uid": "valerie.klein@kunze.io",
                "provider": "email",
                "allow_password_change": false,
                "first_name": "Jessia Hane",
                "last_name": "Cruickshank",
                "username": "dalton_hettinger",
                "created_at": "2020-10-05T15:59:03.385Z",
                "updated_at": "2020-10-05T15:59:03.518Z"
              }
            }

# Group Settings

## Must Update [api/v1/settings/must_update]

### Get [GET]

+ Request Bad

    + Headers

            Access-Token: KWJd5F_JbU8wzg3v_uo94Q
            Client: 2XA2nlfD7t7FzQhKUXygXg
            Uid: dee_bayer@prohaska-pagac.io

+ Response 200 ()

    + Body

            {
              "must_update": true
            }

+ Request Ok

    + Headers

            Access-Token: 1ftmIL3rhmdzyjye6E5eHA
            Client: gpY13JepweWCOT_XCQEKvw
            Uid: darryl_jast@macgyver.org

+ Response 200 ()

    + Body

            {
              "must_update": false
            }

# Group Status

## Status [api/v1/status]

### Get [GET]

+ Request Ok

+ Response 200 ()

    + Body

            {
              "online": true
            }

# Group Users

## Create User [api/v1/users]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: fFYcpFWz6h7txo_7UQxTXA
            Client: U50_YZSoL16c0cBpgr-Qmg
            Uid: chrissy.cormier@herzog.name

    + Body

            {"user":{"email":"not-valid","password":"ThLwAkDoR","username":"michaele.boyle","first_name":"Fr. Josue Mante","last_name":"Towne","uid":"76142394-7e8c-4c5d-a876-616543107187"}}

+ Response 422 ()

    + Body

            {
              "status": "error",
              "data": {
                "id": null,
                "email": "not-valid",
                "allow_password_change": false,
                "first_name": "Fr. Josue Mante",
                "last_name": "Towne",
                "username": "michaele.boyle",
                "created_at": null,
                "updated_at": null,
                "provider": "email",
                "uid": "not-valid"
              },
              "errors": {
                "email": [
                  "is not an email"
                ],
                "full_messages": [
                  "Email is not an email"
                ]
              }
            }

+ Request Ok

    + Headers

            Access-Token: RF2kjjH1rS30gqI8MC64Vw
            Client: TlsYt_JhZugvFvtGJGNJiw
            Uid: cliff@wintheiser-schuppe.co

    + Body

            {"user":{"email":"blake.corkery@reilly.name","password":"Ap1Q96nA69wQ","username":"halley_heaney","first_name":"Odell Ledner","last_name":"Klein","uid":"379a8669-eab0-48c4-93bf-c63af224d030"}}

+ Response 200 ()

    + Headers

            access-token: uLnc0hqhFbIOgZCx6G_yag
            token-type: Bearer
            client: 1lhuj6r36G4B_uJxO5NynA
            expiry: 1664985544
            uid: blake.corkery@reilly.name

    + Body

            {
              "user": {
                "id": 14,
                "email": "blake.corkery@reilly.name",
                "allow_password_change": false,
                "first_name": "Odell Ledner",
                "last_name": "Klein",
                "username": "halley_heaney",
                "created_at": "2020-10-05T15:59:04.939Z",
                "updated_at": "2020-10-05T15:59:04.997Z",
                "provider": "email",
                "uid": "blake.corkery@reilly.name"
              }
            }

## Show User [api/v1/user]

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 94GILoEGsjELT3Hw1PtRHg
            Client: 5CAIctWHf1ckBCEKIGUjOg
            Uid: stephen_wiegand@swaniawski.org

+ Response 200 ()

    + Headers

            access-token: 94GILoEGsjELT3Hw1PtRHg
            token-type: Bearer
            client: 5CAIctWHf1ckBCEKIGUjOg
            expiry: 1664985544
            uid: stephen_wiegand@swaniawski.org

    + Body

            {
              "user": {
                "id": 10,
                "email": "stephen_wiegand@swaniawski.org",
                "name": "Hershel Daniel Hyatt",
                "username": "clair.von"
              }
            }

## Update User [api/v1/user]

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: HwdPtMx9RjcW8bk2_NwzpA
            Client: WQ6koMHmhxCKvtcauQVFRw
            Uid: jere_carter@okuneva-denesik.io

    + Body

            {"user":{"username":"new username"}}

+ Response 200 ()

    + Headers

            access-token: HwdPtMx9RjcW8bk2_NwzpA
            token-type: Bearer
            client: WQ6koMHmhxCKvtcauQVFRw
            expiry: 1664985544
            uid: jere_carter@okuneva-denesik.io

    + Body

            {
              "user": {
                "id": 11,
                "email": "jere_carter@okuneva-denesik.io",
                "name": "Yetta Hansen Williamson",
                "username": "new username"
              }
            }
