FORMAT: 1A
# Rails API Template

# Group Passwords

## Create Password [api/v1/users/password]

### Create [POST]

+ Request Bad

    + Headers

            Access-Token: DA8OpD6NWe00lLT8oLfxDw
            Client: AClIrt54pZQIjXhC0trl-Q
            Uid: francine_gislason@okon.biz

    + Body

            {"email":"notvalid@example.com"}

+ Response 404 ()

    + Body

            {
              "error": "Unable to find user with email 'notvalid@example.com'."
            }

+ Request Ok

    + Headers

            Access-Token: Pq0JI9gYYnrLegEhiY4UcQ
            Client: NxeB5RC-yeC45CAKRnv_5g
            Uid: yer_herman@dooley-mraz.com

    + Body

            {"email":"yer_herman@dooley-mraz.com"}

+ Response 200 ()

    + Body

            {
              "success": true,
              "message": "An email has been sent to 'yer_herman@dooley-mraz.com' containing instructions for resetting your password."
            }

## Update Password [api/v1/users/password]

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: s48YZolzROm5g7ePKPpA0Q
            Client: npxQUFjfzzIuPTbI-dsf5Q
            Uid: louis_douglas@spinka.org

    + Body

            {"password":"123456789","password_confirmation":"123456789"}

+ Response 200 ()

    + Headers

            access-token: s48YZolzROm5g7ePKPpA0Q
            token-type: Bearer
            client: npxQUFjfzzIuPTbI-dsf5Q
            expiry: 1664745533
            uid: louis_douglas@spinka.org

    + Body

            {
              "success": true,
              "data": {
                "id": 593,
                "provider": "email",
                "allow_password_change": false,
                "email": "louis_douglas@spinka.org",
                "uid": "louis_douglas@spinka.org",
                "first_name": "Loyd Erdman LLD",
                "last_name": "Glover",
                "username": "domenic.mueller",
                "created_at": "2020-10-02T21:18:53.104Z",
                "updated_at": "2020-10-02T21:18:53.288Z"
              },
              "message": "Your password has been successfully updated."
            }

## Edit Password [api/v1/users/password/edit]

### Edit [GET]

+ Request Ok

    + Headers

            Access-Token: deHq0KosLdsicNH6zVQV2g
            Client: LN6UFT698Be2BxbVr_pMbQ
            Uid: bennie.davis@dietrich-prosacco.name

+ Response 302 ()

    + Body

            <html><body>You are being <a href="http://127.0.0.1:3000?access-token=ah0n7kPvguhacxuJHNGoew&amp;client=P7fXZbJ6pSSs_hS54Jlo1Q&amp;client_id=P7fXZbJ6pSSs_hS54Jlo1Q&amp;config=&amp;expiry=1664745533&amp;reset_password=true&amp;token=ah0n7kPvguhacxuJHNGoew&amp;uid=bennie.davis%40dietrich-prosacco.name">redirected</a>.</body></html>

# Group Users

## Show User [api/v1/user]

### Show [GET]

+ Request Ok

    + Headers

            Access-Token: 4zejTX_OEMETMFFd3N1Rcg
            Client: QhCprbb1HAuviqGWLLhf_Q
            Uid: kelley@flatley-buckridge.io

+ Response 200 ()

    + Headers

            access-token: 4zejTX_OEMETMFFd3N1Rcg
            token-type: Bearer
            client: QhCprbb1HAuviqGWLLhf_Q
            expiry: 1664745533
            uid: kelley@flatley-buckridge.io

    + Body

            {
              "user": {
                "id": 597,
                "email": "kelley@flatley-buckridge.io",
                "name": "Alan Turner DO Tillman",
                "username": "ray_luettgen"
              }
            }

## Update User [api/v1/user]

### Update [PUT]

+ Request Ok

    + Headers

            Access-Token: M6WUdM--H5lfwKICRuiZzg
            Client: sMd8U1ZaXK2wnodjgZ5w9Q
            Uid: bonnie@bahringer.org

    + Body

            {"user":{"username":"new username"}}

+ Response 200 ()

    + Headers

            access-token: M6WUdM--H5lfwKICRuiZzg
            token-type: Bearer
            client: sMd8U1ZaXK2wnodjgZ5w9Q
            expiry: 1664745534
            uid: bonnie@bahringer.org

    + Body

            {
              "user": {
                "id": 598,
                "email": "bonnie@bahringer.org",
                "name": "Emory Ankunding Hettinger",
                "username": "new username"
              }
            }

## Create User [api/v1/users]

### Create [POST]

+ Request Ok

    + Headers

            Access-Token: GTHhzHySNgpCmPib4FLu7Q
            Client: UsiouAcyo4xv15c9xTRthg
            Uid: frankie@hodkiewicz.io

    + Body

            {"user":{"email":"blair@huel.name","password":"6LtLnZwPy845XcPt","username":"eusebio.dibbert","first_name":"Melita Conroy","last_name":"Wyman","uid":"974ae1a5-2a74-40aa-951e-825b6f2e53f1"}}

+ Response 200 ()

    + Headers

            access-token: gM3tygcbGFAVXMXHn4wsrw
            token-type: Bearer
            client: 63Nn6is3j7-TjiZWBMppRw
            expiry: 1664745534
            uid: blair@huel.name

    + Body

            {
              "user": {
                "id": 600,
                "email": "blair@huel.name",
                "allow_password_change": false,
                "first_name": "Melita Conroy",
                "last_name": "Wyman",
                "username": "eusebio.dibbert",
                "created_at": "2020-10-02T21:18:54.243Z",
                "updated_at": "2020-10-02T21:18:54.298Z",
                "provider": "email",
                "uid": "blair@huel.name"
              }
            }
